Update pp-deploy-bsispdev.yml

diff --git a/.github/workflows/pp-deploy-bsispdev.yml b/.github/workflows/pp-deploy-bsispdev.yml
--- a/.github/workflows/pp-deploy-bsispdev.yml
+++ b/.github/workflows/pp-deploy-bsispdev.yml
@@ -173,6 +173,9 @@ jobs:
           if [ ! -s missing.xml ]; then
             echo "### ✅ No missing dependencies found" >> $GITHUB_STEP_SUMMARY
             exit 0
+          else
+            echo "❌ Deployment failed due to missing dependencies" >> $GITHUB_STEP_SUMMARY
+            exit 1
           fi
           
       #install xmllint
